// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Prompt editor AMD module for local_lid.
 *
 * Handles the prompt template editor UI that appears on:
 *   - Site admin settings page (Site Administration → Plugins → local_lid)
 *   - Course-level prompt override (if admin has not locked the prompt)
 *   - Forum-level prompt override (if admin has not locked the prompt)
 *
 * Features:
 *   File upload     — accepts .md files via drag-drop or browse button;
 *                     file content replaces the textarea value.
 *   Character count — live count shown below the textarea.
 *   Dirty flag      — warns on page unload if there are unsaved changes.
 *   Save (AJAX)     — course/forum level saves via ajax.php save_prompt action.
 *                     Admin settings page uses Moodle's standard form submit.
 *   Reset buttons   — "Reset to site default" and "Reset to plugin default"
 *                     with confirmation dialogs.
 *   Read-only mode  — when prompt_locked = 1, all edit controls are hidden
 *                     and the textarea is disabled. The module still runs but
 *                     only initialises the character count display.
 *
 * Expected DOM structure (rendered by prompt_editor.mustache or settings.php):
 *
 *   <div class="lid-prompt-editor" data-courseid="N" data-locked="0|1">
 *     <textarea id="lid-prompt-textarea" rows="20"></textarea>
 *     <div class="lid-prompt-footer">
 *       <span class="lid-prompt-charcount"></span>
 *       <div class="lid-prompt-actions">
 *         <label class="lid-btn lid-btn-secondary lid-prompt-upload-label">
 *           Upload .md
 *           <input type="file" class="lid-prompt-file-input" accept=".md">
 *         </label>
 *         <button class="lid-btn lid-btn-secondary lid-prompt-reset-course">
 *           Reset to site default
 *         </button>
 *         <button class="lid-btn lid-btn-secondary lid-prompt-reset-plugin">
 *           Reset to plugin default
 *         </button>
 *         <button class="lid-btn lid-btn-primary lid-prompt-save">
 *           Save prompt
 *         </button>
 *       </div>
 *     </div>
 *   </div>
 *
 * On the admin settings page, Moodle renders the textarea directly via
 * admin_setting_configtextarea. In that case the module targets the textarea
 * by its Moodle-generated id (id_s_local_lid_prompt_template) and attaches
 * only the file upload and character count — saving is handled by the
 * standard settings form submit button.
 *
 * @module     local_lid/prompt_editor
 * @copyright  2026 Learning Intelligence Dashboard Project Contributors
 * @license    https://www.gnu.org/licenses/gpl-3.0.html GNU GPL v3 or later
 */
define(['core/str', 'core/notification'], function(Str, Notification) {

    'use strict';

    // =========================================================================
    // Constants
    // =========================================================================

    /** Moodle admin settings textarea id — generated by admin_setting_configtextarea. */
    var ADMIN_TEXTAREA_ID = 'id_s_local_lid_prompt_template';

    /** Selector for the custom prompt editor wrapper. */
    var EDITOR_SELECTOR = '.lid-prompt-editor';

    /** Maximum file size accepted for .md upload (bytes). 512 KB is generous for a prompt. */
    var MAX_FILE_BYTES = 512 * 1024;

    // =========================================================================
    // Public entry point
    // =========================================================================

    /**
     * Initialise the prompt editor.
     *
     * Called from the Mustache template or from settings.php via:
     *   $PAGE->requires->js_call_amd('local_lid/prompt_editor', 'init', []);
     *
     * Detects whether we are on the admin settings page (targets the Moodle
     * admin textarea directly) or on a course/forum page (targets the custom
     * wrapper element).
     */
    function init() {
        // Admin settings page — attach to Moodle's generated textarea.
        var adminTextarea = document.getElementById(ADMIN_TEXTAREA_ID);
        if (adminTextarea) {
            initAdminTextarea(adminTextarea);
        }

        // Course/forum level editors.
        document.querySelectorAll(EDITOR_SELECTOR).forEach(function(wrapper) {
            initEditorWrapper(wrapper);
        });
    }

    // =========================================================================
    // Admin settings page init
    // =========================================================================

    /**
     * Attach file upload and character count to the admin settings textarea.
     *
     * On the admin settings page Moodle renders its own form and save button,
     * so we only add the .md upload affordance and the live character count.
     * No AJAX save or reset buttons are injected here.
     *
     * @param {HTMLTextAreaElement} textarea
     */
    function initAdminTextarea(textarea) {
        // Insert a character count span immediately after the textarea.
        var countEl = document.createElement('div');
        countEl.style.cssText = 'font-size:11px;color:#5a7090;font-family:"DM Mono",monospace;' +
                                'margin-top:4px;margin-bottom:8px';
        textarea.parentNode.insertBefore(countEl, textarea.nextSibling);
        updateCharCount(textarea, countEl);
        textarea.addEventListener('input', function() {
            updateCharCount(textarea, countEl);
        });

        // Insert a file upload button after the count.
        var uploadLabel = buildUploadLabel();
        countEl.parentNode.insertBefore(uploadLabel, countEl.nextSibling);

        var fileInput = uploadLabel.querySelector('input[type="file"]');
        fileInput.addEventListener('change', function(e) {
            handleFileSelect(e.target.files[0], textarea, countEl);
            e.target.value = ''; // Reset so the same file can be re-selected.
        });

        // Drag-drop on the textarea itself.
        attachDragDrop(textarea, function(file) {
            handleFileSelect(file, textarea, countEl);
        });
    }

    // =========================================================================
    // Course/forum level editor init
    // =========================================================================

    /**
     * Fully initialise a .lid-prompt-editor wrapper element.
     *
     * @param {HTMLElement} wrapper
     */
    function initEditorWrapper(wrapper) {
        var textarea  = wrapper.querySelector('#lid-prompt-textarea, textarea');
        var countEl   = wrapper.querySelector('.lid-prompt-charcount');
        var fileInput = wrapper.querySelector('.lid-prompt-file-input');
        var saveBtn   = wrapper.querySelector('.lid-prompt-save');
        var resetCourseBtn = wrapper.querySelector('.lid-prompt-reset-course');
        var resetPluginBtn = wrapper.querySelector('.lid-prompt-reset-plugin');
        var locked    = wrapper.dataset.locked === '1';
        var courseid  = parseInt(wrapper.dataset.courseid, 10) || 0;

        if (!textarea) {
            return;
        }

        // Character count.
        if (countEl) {
            updateCharCount(textarea, countEl);
            textarea.addEventListener('input', function() {
                updateCharCount(textarea, countEl);
            });
        }

        // Read-only mode — nothing else to wire up.
        if (locked) {
            textarea.setAttribute('disabled', 'disabled');
            textarea.setAttribute('readonly', 'readonly');
            return;
        }

        // Dirty flag — warn on navigation away from unsaved changes.
        var dirty = false;
        textarea.addEventListener('input', function() {
            dirty = true;
        });
        window.addEventListener('beforeunload', function(e) {
            if (dirty) {
                e.preventDefault();
                e.returnValue = '';
            }
        });

        // File upload via input[type=file].
        if (fileInput) {
            fileInput.addEventListener('change', function(e) {
                handleFileSelect(e.target.files[0], textarea, countEl, function() {
                    dirty = true;
                });
                e.target.value = '';
            });
        }

        // Drag-drop on textarea.
        attachDragDrop(textarea, function(file) {
            handleFileSelect(file, textarea, countEl, function() {
                dirty = true;
            });
        });

        // AJAX save button (course/forum level only).
        if (saveBtn && courseid) {
            saveBtn.addEventListener('click', function() {
                savePrompt(courseid, textarea.value, saveBtn, function() {
                    dirty = false;
                });
            });
        }

        // Reset to site default.
        if (resetCourseBtn && courseid) {
            resetCourseBtn.addEventListener('click', function() {
                confirmReset(
                    'Reset this course prompt to the site-level default?',
                    function() {
                        resetToSiteDefault(courseid, textarea, countEl, function() {
                            dirty = false;
                        });
                    }
                );
            });
        }

        // Reset to plugin default (admin only — shown when data-show-plugin-reset="1").
        if (resetPluginBtn) {
            resetPluginBtn.addEventListener('click', function() {
                confirmReset(
                    'Reset to the prompt shipped with the plugin? This will replace the current site-level prompt.',
                    function() {
                        resetToPluginDefault(textarea, countEl, function() {
                            dirty = false;
                        });
                    }
                );
            });
        }
    }

    // =========================================================================
    // File upload handling
    // =========================================================================

    /**
     * Read a File object and load its content into the textarea.
     *
     * Only accepts .md files. Validates size. On success, replaces the
     * textarea value and updates the character count. Calls onLoaded()
     * after successful load.
     *
     * @param {File|undefined} file
     * @param {HTMLTextAreaElement} textarea
     * @param {HTMLElement|null}    countEl
     * @param {Function}           [onLoaded]
     */
    function handleFileSelect(file, textarea, countEl, onLoaded) {
        if (!file) {
            return;
        }

        if (!file.name.toLowerCase().endsWith('.md')) {
            showInlineError(textarea, 'Only .md files are accepted.');
            return;
        }

        if (file.size > MAX_FILE_BYTES) {
            showInlineError(textarea, 'File is too large (max 512 KB).');
            return;
        }

        var reader = new FileReader();
        reader.onload = function(e) {
            var content = e.target.result;
            if (typeof content !== 'string' || content.trim() === '') {
                showInlineError(textarea, 'File appears to be empty.');
                return;
            }
            textarea.value = content;
            if (countEl) {
                updateCharCount(textarea, countEl);
            }
            showInlineSuccess(textarea, 'File loaded: ' + file.name);
            if (typeof onLoaded === 'function') {
                onLoaded();
            }
        };
        reader.onerror = function() {
            showInlineError(textarea, 'Could not read the file.');
        };
        reader.readAsText(file);
    }

    /**
     * Attach drag-and-drop file handling to an element.
     *
     * Visual feedback is applied to the element during drag. On drop,
     * the first file is passed to the onFile callback.
     *
     * @param {HTMLElement} el
     * @param {Function}    onFile  Called with the dropped File object.
     */
    function attachDragDrop(el, onFile) {
        el.addEventListener('dragover', function(e) {
            e.preventDefault();
            e.stopPropagation();
            el.style.outline = '2px dashed #00e5ff';
            el.style.outlineOffset = '-2px';
        });

        el.addEventListener('dragleave', function(e) {
            e.preventDefault();
            el.style.outline = '';
            el.style.outlineOffset = '';
        });

        el.addEventListener('drop', function(e) {
            e.preventDefault();
            e.stopPropagation();
            el.style.outline = '';
            el.style.outlineOffset = '';
            var file = e.dataTransfer && e.dataTransfer.files && e.dataTransfer.files[0];
            if (file) {
                onFile(file);
            }
        });
    }

    // =========================================================================
    // AJAX save
    // =========================================================================

    /**
     * Save a course-level prompt override via ajax.php.
     *
     * @param {number}          courseid
     * @param {string}          promptText
     * @param {HTMLButtonElement} btn
     * @param {Function}        [onSuccess]
     */
    function savePrompt(courseid, promptText, btn, onSuccess) {
        if (!promptText || !promptText.trim()) {
            showInlineError(btn, 'Prompt cannot be empty.');
            return;
        }

        setButtonWorking(btn, true);

        var body = new URLSearchParams();
        body.set('action',   'save_prompt');
        body.set('courseid', courseid);
        body.set('prompt',   promptText);
        body.set('sesskey',  M.cfg.sesskey);

        fetch(M.cfg.wwwroot + '/local/lid/ajax.php', {
            method:  'POST',
            headers: {'Content-Type': 'application/x-www-form-urlencoded'},
            body:    body.toString(),
        })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            setButtonWorking(btn, false);
            if (data.error) {
                showToast(data.message || 'Save failed.', 'error');
            } else {
                showToast(data.message || 'Prompt saved.', 'success');
                if (typeof onSuccess === 'function') {
                    onSuccess();
                }
            }
        })
        .catch(function() {
            setButtonWorking(btn, false);
            showToast('Save failed. Check your connection.', 'error');
        });
    }

    // =========================================================================
    // Reset actions
    // =========================================================================

    /**
     * Reset a course-level prompt to the site default by fetching it via AJAX
     * and loading it into the textarea.
     *
     * Implementation: sends save_prompt with an empty string which the server
     * interprets as "delete course override, fall back to site default". Then
     * reloads the page so the textarea reflects the inherited value.
     *
     * @param {number}                courseid
     * @param {HTMLTextAreaElement}   textarea
     * @param {HTMLElement|null}      countEl
     * @param {Function}             [onDone]
     */
    function resetToSiteDefault(courseid, textarea, countEl, onDone) {
        var body = new URLSearchParams();
        body.set('action',   'save_prompt');
        body.set('courseid', courseid);
        body.set('prompt',   '__RESET_TO_SITE_DEFAULT__');
        body.set('sesskey',  M.cfg.sesskey);

        fetch(M.cfg.wwwroot + '/local/lid/ajax.php', {
            method:  'POST',
            headers: {'Content-Type': 'application/x-www-form-urlencoded'},
            body:    body.toString(),
        })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                showToast(data.message || 'Reset failed.', 'error');
            } else {
                showToast('Reset to site default. Refreshing…', 'success');
                if (typeof onDone === 'function') {
                    onDone();
                }
                setTimeout(function() { window.location.reload(); }, 800);
            }
        })
        .catch(function() {
            showToast('Reset failed. Check your connection.', 'error');
        });
    }

    /**
     * Reset the admin-level prompt to the plugin default.
     *
     * Fetches the default prompt text from the server via a dedicated reset
     * action, then loads it into the textarea. The admin still needs to submit
     * the settings form to persist it.
     *
     * @param {HTMLTextAreaElement}  textarea
     * @param {HTMLElement|null}     countEl
     * @param {Function}            [onDone]
     */
    function resetToPluginDefault(textarea, countEl, onDone) {
        var body = new URLSearchParams();
        body.set('action',  'reset_prompt_default');
        body.set('sesskey', M.cfg.sesskey);

        fetch(M.cfg.wwwroot + '/local/lid/ajax.php', {
            method:  'POST',
            headers: {'Content-Type': 'application/x-www-form-urlencoded'},
            body:    body.toString(),
        })
        .then(function(r) { return r.json(); })
        .then(function(data) {
            if (data.error) {
                showToast(data.message || 'Reset failed.', 'error');
            } else if (data.prompt) {
                textarea.value = data.prompt;
                if (countEl) {
                    updateCharCount(textarea, countEl);
                }
                showToast('Plugin default loaded. Submit the form to save.', 'success');
                if (typeof onDone === 'function') {
                    onDone();
                }
            }
        })
        .catch(function() {
            showToast('Reset failed. Check your connection.', 'error');
        });
    }

    // =========================================================================
    // UI helpers
    // =========================================================================

    /**
     * Update the character count display.
     *
     * @param {HTMLTextAreaElement} textarea
     * @param {HTMLElement}         countEl
     */
    function updateCharCount(textarea, countEl) {
        var count = textarea.value.length;
        countEl.textContent = count.toLocaleString() + ' characters';
    }

    /**
     * Build the upload label/button element.
     *
     * @return {HTMLLabelElement}
     */
    function buildUploadLabel() {
        var label = document.createElement('label');
        label.style.cssText = 'display:inline-flex;align-items:center;gap:6px;' +
                              'padding:7px 14px;border-radius:4px;cursor:pointer;' +
                              'font-family:"DM Mono",monospace;font-size:11px;' +
                              'letter-spacing:1px;text-transform:uppercase;' +
                              'border:1px solid #1e2d44;color:#5a7090;' +
                              'background:transparent;transition:all 0.2s;' +
                              'margin-top:6px;';
        label.textContent = 'Upload .md';

        var input = document.createElement('input');
        input.type   = 'file';
        input.accept = '.md';
        input.style.cssText = 'position:absolute;width:1px;height:1px;' +
                              'opacity:0;overflow:hidden;clip:rect(0,0,0,0)';
        label.appendChild(input);

        label.addEventListener('mouseenter', function() {
            label.style.borderColor = '#7b61ff';
            label.style.color = '#7b61ff';
        });
        label.addEventListener('mouseleave', function() {
            label.style.borderColor = '#1e2d44';
            label.style.color = '#5a7090';
        });

        return label;
    }

    /**
     * Show a brief inline success message near an element.
     *
     * @param {HTMLElement} anchor
     * @param {string}      message
     */
    function showInlineSuccess(anchor, message) {
        showInlineMessage(anchor, message, '#00ff9d');
    }

    /**
     * Show a brief inline error message near an element.
     *
     * @param {HTMLElement} anchor
     * @param {string}      message
     */
    function showInlineError(anchor, message) {
        showInlineMessage(anchor, message, '#ff6b35');
    }

    /**
     * Insert a temporary inline message immediately after an anchor element.
     *
     * @param {HTMLElement} anchor
     * @param {string}      message
     * @param {string}      color    CSS color value.
     */
    function showInlineMessage(anchor, message, color) {
        // Remove any existing inline message.
        var existing = anchor.parentNode &&
                       anchor.parentNode.querySelector('.lid-inline-msg');
        if (existing) {
            existing.parentNode.removeChild(existing);
        }

        var el = document.createElement('div');
        el.className = 'lid-inline-msg';
        el.style.cssText = 'font-size:11px;font-family:"DM Mono",monospace;' +
                           'color:' + color + ';margin-top:4px;transition:opacity 0.3s';
        el.textContent = message;

        if (anchor.parentNode) {
            anchor.parentNode.insertBefore(el, anchor.nextSibling);
        }

        setTimeout(function() {
            el.style.opacity = '0';
            setTimeout(function() {
                if (el.parentNode) {
                    el.parentNode.removeChild(el);
                }
            }, 300);
        }, 3000);
    }

    /**
     * Set a button into working (disabled + spinner text) or normal state.
     *
     * @param {HTMLButtonElement} btn
     * @param {boolean}           working
     */
    function setButtonWorking(btn, working) {
        if (!btn) {
            return;
        }
        btn.disabled = working;
        if (working) {
            btn.dataset.originalText = btn.textContent;
            btn.textContent = '⏳ Saving…';
        } else {
            btn.textContent = btn.dataset.originalText || btn.textContent;
        }
    }

    /**
     * Show a confirmation dialog using Moodle's native confirm() fallback.
     *
     * We use window.confirm() rather than core/modal to keep the dependency
     * surface minimal. For a settings action this is appropriate.
     *
     * @param {string}   message
     * @param {Function} onConfirm
     */
    function confirmReset(message, onConfirm) {
        if (window.confirm(message)) {
            onConfirm();
        }
    }

    /**
     * Show a toast notification (reuses the same pattern as dashboard.js).
     *
     * @param {string} message
     * @param {string} [type='info']
     */
    function showToast(message, type) {
        type = type || 'info';
        var colors = {
            info:    '#00e5ff',
            success: '#00ff9d',
            warn:    '#ff6b35',
            error:   '#ff3c3c',
        };
        var toast = document.createElement('div');
        toast.style.cssText = [
            'position:fixed',
            'bottom:24px',
            'right:24px',
            'z-index:9999',
            'background:#141d2e',
            'border:1px solid ' + (colors[type] || colors.info),
            'padding:12px 20px',
            'border-radius:6px',
            'font-family:\'DM Mono\',monospace',
            'font-size:11px',
            'color:' + (colors[type] || colors.info),
            'transform:translateY(80px)',
            'opacity:0',
            'transition:all 0.3s',
            'pointer-events:none',
            'max-width:360px',
            'line-height:1.4',
        ].join(';');
        toast.textContent = message;
        document.body.appendChild(toast);

        requestAnimationFrame(function() {
            requestAnimationFrame(function() {
                toast.style.transform = 'translateY(0)';
                toast.style.opacity   = '1';
            });
        });

        setTimeout(function() {
            toast.style.transform = 'translateY(80px)';
            toast.style.opacity   = '0';
            setTimeout(function() {
                if (toast.parentNode) {
                    toast.parentNode.removeChild(toast);
                }
            }, 300);
        }, 3500);
    }

    // =========================================================================
    // Public API
    // =========================================================================

    return {
        init: init,
    };
});
